
export class Cajero {


  idCajero?: number;
  nombreCajero: string;
  apellidoCajero?: string;
  generoCajero: string;
  usuarioCajero: string;
  pswdCajero: string;
  estadoCajero: string;

  constructor() {
    this.idCajero = 0;
    this.nombreCajero = '';
    this.apellidoCajero = '';
    this.generoCajero = '';
    this.usuarioCajero = '';
    this.pswdCajero = '';
    this.estadoCajero = '';
  }


}